### ISSUE TITLE
Please correct your requirements.txt file naming

### ISSUE THREAD

**Issue by esaiaswt** [Ka-ch0w/Mini-Project#1]
please do as above and include pygame in this file

**Comment by Ka-ch0w** [comment]
Hi William Tan,

I wanted to personally thank you for bringing the issue with [specific issue] to my attention. Your keen eye and feedback are incredibly valuable to us, and we genuinely appreciate the time you took to help improve our game.

We've addressed the issue and are committed to making Chrome Dinosaur Game the best experience it can be for all our players. If you have any more feedback or run into any other issues, please don't hesitate to reach out.

Thanks again for your support and for being a part of our community!

Best regards,

Khairul Akmal, Quantum Quests
