### ISSUE TITLE
Do include your sub folder with resources

### ISSUE THREAD

**Issue by esaiaswt** [Ka-ch0w/Mini-Project#2]
Below is the error: 

pygame 2.6.0 (SDL 2.28.4, Python 3.12.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "c:\Users\esaia\OneDrive\Documents\Projects\Mini-Project\main.py", line 12, in <module>
    RUNNING = [pygame.image.load(os.path.join("Assets/Dino", "DinoRun1.png")),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: No file 'Assets/Dino\DinoRun1.png' found in working directory 'C:\Users\esaia\OneDrive\Documents\Projects\Mini-Project'.

**Comment by Ka-ch0w** [comment]
Hi William Tan,

I wanted to personally thank you for bringing the issue with [specific issue] to my attention. Your keen eye and feedback are incredibly valuable to us, and we genuinely appreciate the time you took to help improve our game.

We've addressed the issue and are committed to making Chrome Dinosaur Game the best experience it can be for all our players. If you have any more feedback or run into any other issues, please don't hesitate to reach out.

Thanks again for your support and for being a part of our community!

Best regards,

Khairul Akmal, Quantum Quests
